MaestroDetalle/Controllers/VentasController.cs
using MaestroDetalle.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MaestroDetalle.Controllers
{
    public class VentasController : Controller
    {
        private tiendaContext db = new tiendaContext();

        // GET: Ventas
        public ActionResult NuevaOrden()
        {
            Clase_OrdenVista OrdenVista = new Clase_OrdenVista();
            OrdenVista.ClaseCliente = new ClaseCliente_Orden();
            OrdenVista.ClaseProducto = new List<ClaseProductoOrden>();
            Session["OrdenVista"] = OrdenVista;

        var list = db.ClaseClientes.ToList();
            ViewBag.Id_Cliente = new SelectList(list, "Id_Cliente", "Nombre_Compañia_Cliente");

            return View(OrdenVista);
        }


        [HttpPost]
        public ActionResult NuevaOrden(Clase_OrdenVista OrdenVista) {

            OrdenVista = Session["OrdenVista"] as Clase_OrdenVista;
            int Id_Clientes = int.Parse(Request["Id_Cliente"]);
            DateTime fechaOrden = Convert.ToDateTime(Request["ClaseCliente.Fecha_Orden"]);

            ClaseOrdenes neworder = new ClaseOrdenes
            {
                Id_Cliente = Id_Clientes,
                Fecha_Orden = fechaOrden
            };

            db.ClaseOrdenes.Add(neworder);
            db.SaveChanges();
            int ultimaordenid = db.ClaseOrdenes.ToList().Select(o=> o.Id_Ordenes).Max();

            foreach (ClaseProductoOrden item in OrdenVista.ClaseProducto)
            {
                var detalle = new ClaseDetalleOrden()
                {
                    Id_Ordenes= ultimaordenid,
                    Id_Producto=item.Id_Producto,
                    Cantidad_ClasDetOrd = item.Cantidad_ClasDetOrd,
                    precio_ClasDetOrd= item.Unitprice_Producto,
                   


                };

                db.ClaseDetalleOrdenes.Add(detalle);
            }

            db.SaveChanges();

            OrdenVista = Session["OrdenVista"] as Clase_OrdenVista;
            var list = db.ClaseClientes.ToList();
            ViewBag.Id_Cliente = new SelectList(list, "Id_Cliente", "Nombre_Compañia_Cliente");

            return View(OrdenVista);
        }




        [HttpGet]
        public ActionResult AgregarProducto()
        {

            var listp = db.ClaseProductos.ToList();
            ViewBag.Id_Producto = new SelectList(listp, "Id_Producto", "Nombre_Producto");
            return View();

        }

        [HttpPost]
        public ActionResult AgregarProducto(ClaseProductoOrden productorden)
        {
            var OrdenVista = Session["OrdenVista"] as Clase_OrdenVista;
            var productid = int.Parse(Request["Id_Producto"]);
            var producto = db.ClaseProductos.Find(productid);

            productorden = new ClaseProductoOrden()
            {
                Id_Producto = producto.Id_Producto,
                Nombre_Producto=producto.Nombre_Producto,
                Unitprice_Producto= producto.Unitprice_Producto,
                Cantidad_ClasDetOrd= int.Parse(Request["Cantidad_ClasDetOrd"])
        };

            OrdenVista.ClaseProducto.Add(productorden);


            var list = db.ClaseClientes.ToList();
            ViewBag.Id_Cliente = new SelectList(list, "Id_Cliente", "Nombre_Compañia_Cliente");
            var listp = db.ClaseProductos.ToList();
            ViewBag.Id_Producto = new SelectList(listp, "Id_Producto", "Nombre_Producto");
            return View("NuevaOrden", OrdenVista);

        }
    }
}

MaestroDetalle/Views/Ventas/AgregarProducto.cshtml
@model MaestroDetalle.Models.ClaseProductoOrden


@{
    ViewBag.Title = "AgregarProducto";
}

<h2>Agregar Producto</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Cantidad_ClasDetOrd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cantidad_ClasDetOrd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cantidad_ClasDetOrd, "", new { @class = "text-danger" })
            </div>
        </div>

    

        <div class="form-group">
            @Html.LabelFor(model => model.Id_Producto, "PRODUCTO", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_Producto", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Id_Producto, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("ATRAS", "NuevaOrden", new { }, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MaestroDetalle/Views/Ventas/NuevaOrden.cshtml
@model MaestroDetalle.Models.Clase_OrdenVista

@{
    ViewBag.Title = "NuevaOrden";
}

<h2>NuevaOrden</h2>
@using (Html.BeginForm("NuevaOrden","Ventas",FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ClaseCliente.Fecha_Orden, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClaseCliente.Fecha_Orden, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClaseCliente.Fecha_Orden, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClaseCliente.Id_Cliente, "Cliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Id_Cliente", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClaseCliente.Id_Cliente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("agregar producto", "AgregarProducto", new { }, new {@class="btn btn-default"})
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    
      
    </div>








    <table class="table">
        <tr>
           
            <th>
                @Html.DisplayNameFor(model => model.Titulo.Nombre_Producto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo.Cantidad_ClasDetOrd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo.Unitprice_Producto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Titulo.parcial)
            </th>
            <th></th>
        </tr>

        @for (int i=0;i<Model.ClaseProducto.Count;i++)
        {
            <tr>
                
                <td>
                    @Html.DisplayFor(modelItem => Model.ClaseProducto[i].Nombre_Producto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.ClaseProducto[i].Cantidad_ClasDetOrd)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.ClaseProducto[i].Unitprice_Producto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.ClaseProducto[i].parcial)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = Model.ClaseProducto[i].Id_Producto}) |
                  
                    @Html.ActionLink("Delete", "Delete", new { id = Model.ClaseProducto[i].Id_Producto })
                </td>
            </tr>
        }

    </table>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}