MaestroDetalle/Models/ClaseProducto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MaestroDetalle.Models
{
    public class ClaseProducto
    {
        [Key]
        public int Id_Producto { set; get; }

        [Display(Name = "NOMBRE")]
        public string Nombre_Producto { set; get; }

        [Display(Name = "PRECIO")]
        [DisplayFormat(DataFormatString = "{0:C2}", ApplyFormatInEditMode = false)]
        public decimal Unitprice_Producto { set; get; }

        // relacion con ClaseDetalleOrden
        public virtual ICollection<ClaseDetalleOrden> ClaseDetalleOrden { set; get; }
    }
}

MaestroDetalle/Controllers/ClaseProductosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MaestroDetalle.Models;

namespace MaestroDetalle.Controllers
{
    public class ClaseProductosController : Controller
    {
        private tiendaContext db = new tiendaContext();

        // GET: ClaseProductos
        public ActionResult Index()
        {
            return View(db.ClaseProductos.ToList());
        }

        // GET: ClaseProductos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClaseProducto claseProducto = db.ClaseProductos.Find(id);
            if (claseProducto == null)
            {
                return HttpNotFound();
            }
            return View(claseProducto);
        }

        // GET: ClaseProductos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ClaseProductos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_Producto,Nombre_Producto,Unitprice_Producto")] ClaseProducto claseProducto)
        {
            if (ModelState.IsValid)
            {
                db.ClaseProductos.Add(claseProducto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(claseProducto);
        }

        // GET: ClaseProductos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClaseProducto claseProducto = db.ClaseProductos.Find(id);
            if (claseProducto == null)
            {
                return HttpNotFound();
            }
            return View(claseProducto);
        }

        // POST: ClaseProductos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_Producto,Nombre_Producto,Unitprice_Producto")] ClaseProducto claseProducto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(claseProducto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(claseProducto);
        }

        // GET: ClaseProductos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClaseProducto claseProducto = db.ClaseProductos.Find(id);
            if (claseProducto == null)
            {
                return HttpNotFound();
            }
            return View(claseProducto);
        }

        // POST: ClaseProductos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ClaseProducto claseProducto = db.ClaseProductos.Find(id);
            db.ClaseProductos.Remove(claseProducto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        public ActionResult BusquedaFiltro (string Nombre_Producto) {

            var BusquedaProduct = from bp in db.ClaseProductos select bp;

            if (!string.IsNullOrEmpty(Nombre_Producto)) {

                BusquedaProduct = BusquedaProduct.Where(np => np.Nombre_Producto.Contains(Nombre_Producto));

              
            }

            return View(BusquedaProduct);


        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MaestroDetalle/Views/ClaseProductos/BusquedaFiltro.cshtml
@model IEnumerable<MaestroDetalle.Models.ClaseProducto>

@{
    ViewBag.Title = "BusquedaFiltro";
}

<h2>BusquedaFiltro</h2>





    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre_Producto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Unitprice_Producto)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre_Producto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Unitprice_Producto)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id_Producto }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id_Producto }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id_Producto })
                </td>
            </tr>
        }

    </table>

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">

        @Html.ActionLink("ATRAS", "Index", new { }, new { @class = "btn btn-default" })
    </div>
</div>

MaestroDetalle/Views/ClaseProductos/Create.cshtml
@model MaestroDetalle.Models.ClaseProducto

@{
    ViewBag.Title = "Create";
}

<h2>PRODUCTO</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ingresar datos del nuevo producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
           <label class="control-label col-md-2">
               NOMBRE
           </label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre_Producto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre_Producto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">
                PRECIO
            </label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Unitprice_Producto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Unitprice_Producto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("ATRAS", "Index", new { }, new { @class = "btn btn-default" })
</div>

MaestroDetalle/Views/ClaseProductos/Delete.cshtml
@model MaestroDetalle.Models.ClaseProducto

@{
    ViewBag.Title = "Delete";
}

<h2>BORRAR PRODUCTO</h2>

<h3>Estas seguro de querer eliminar el producto?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre_Producto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre_Producto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Unitprice_Producto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unitprice_Producto)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> 
           @Html.ActionLink("Atras", "Index", new { }, new { @class = "btn btn-default" })
        </div>
    }
</div>

MaestroDetalle/Views/ClaseProductos/Details.cshtml
@model MaestroDetalle.Models.ClaseProducto

@{
    ViewBag.Title = "Details";
}

<h2>DETALLE</h2>

<div>
    <h4>ClaseProducto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            
            @Html.LabelFor(model => model.Nombre_Producto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre_Producto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Unitprice_Producto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unitprice_Producto)
        </dd>

    </dl>
</div>
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
       @Html.ActionLink("EDITAR", "Edit", new { id = Model.Id_Producto }, new { @class = "btn btn-default" })
        @Html.ActionLink("ATRAS", "Index", new { }, new { @class = "btn btn-default" })
    </div>
</div>
   

MaestroDetalle/Views/ClaseProductos/Edit.cshtml
@model MaestroDetalle.Models.ClaseProducto

@{
    ViewBag.Title = "Edit";
}

<h2>EDITAR</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id_Producto)

        <div class="form-group">
           <label class="control-label col-md-2">
            NOMBRE
           </label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre_Producto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre_Producto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">
                PRECIO
            </label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Unitprice_Producto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Unitprice_Producto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
     
    @Html.ActionLink("Atras", "Index", new { }, new { @class = "btn btn-default" })
</div>

MaestroDetalle/Views/ClaseProductos/Index.cshtml
@model IEnumerable<MaestroDetalle.Models.ClaseProducto>

@{
    ViewBag.Title = "Index";
}

<h2>LISTADO DE PRODUCTOS</h2>


<br/>


@using (Html.BeginForm("BusquedaFiltro", "ClaseProductos", FormMethod.Get))
{
    <div class="form-control-static">
        <div class="form-group">
            <label class="control-label col-md-2">
                Busqueda por nombre
            </label>
            <div class="col-md-10">
                @Html.TextBox("Nombre_Producto")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Busqueda" class="btn btn-default" />
            </div>
        </div>

        

    </div>

}






        <p>
            @Html.ActionLink("CREAR NUEVO", "Create", new { }, new { @class = "btn btn-default" })
        </p>
        <table class="table">
            <tr>
                <th>
                    NOMBRE

                </th>
                <th>
                    PRECIO UNIDAD
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre_Producto)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Unitprice_Producto)
                    </td>
                    <td>
                        @Html.ActionLink("EDITAR", "Edit", new { id = item.Id_Producto }, new { @class = "btn btn-default" })
                        @Html.ActionLink("DETALLE", "Details", new { id = item.Id_Producto }, new { @class = "btn btn-default" })

                        @Html.ActionLink("BORRAR", "Delete", new { id = item.Id_Producto }, new { @class = "btn btn-default" })
                    </td>
                </tr>
            }

        </table>